eureka:
  instance:
    prefer-ip-address: true
    ip-address: 47.96.224.108
    
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

spring:
  datasource:
    url: jdbc:mysql://47.96.224.108:3306/customerdb?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
        
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.lxy.model
